// Importing the createSlice function from '@reduxjs/toolkit'
import { createSlice } from "@reduxjs/toolkit";

// Defining the initial state for the authentication slice of the Redux store
const initialAuthState = {
  isAuthenticated: false, // Initially, the user is not authenticated
};

// Creating a slice of the Redux store for managing the authentication state
const authSlice = createSlice({
  // Name of the slice, used to identify actions and state in the Redux store
  name: "authentication",

  // Initial state for the slice
  initialState: initialAuthState,

  // Reducer functions for handling actions that modify the state
  reducers: {
    // Reducer for setting the isAuthenticated state to true, indicating a successful login
    login(state) {
      state.isAuthenticated = true; // Setting isAuthenticated to true
    },

    // Reducer for setting the isAuthenticated state to false, indicating a logout
    logout(state) {
      state.isAuthenticated = false; // Setting isAuthenticated to false
    },
  },
});

// Exporting action creators generated by createSlice for the authentication slice
export const authActions = authSlice.actions;

// Exporting the reducer function generated by createSlice for the authentication slice
export default authSlice.reducer;

/*
The createSlice function from Redux Toolkit is used to define a slice of the Redux store that manages the authentication state.
The slice is given a name ('authentication') to identify it within the Redux store.
The initial state for the authentication slice is defined with a property isAuthenticated initialized to false, indicating that the user is not authenticated initially.
Inside the reducers object, individual reducer functions are defined to handle specific actions:
login: Sets the isAuthenticated state to true, indicating a successful login.
logout: Sets the isAuthenticated state to false, indicating a logout.
Action creators generated by createSlice are exported as authActions.
The reducer function generated by createSlice for the authentication slice is exported as the default export.
*/
