// Importing the createSlice function from '@reduxjs/toolkit'
import { createSlice } from "@reduxjs/toolkit";

// Defining the initial state for the counter slice of the Redux store
const initialCounterState = { counter: 0, showCounter: true };

// Creating a slice of the Redux store for managing the counter state
const counterSlice = createSlice({
  // Name of the slice, used to identify actions and state in the Redux store
  name: "counter",

  // Initial state for the slice
  initialState: initialCounterState,

  // Reducer functions for handling actions that modify the state
  reducers: {
    // Reducer for incrementing the counter by 1
    increment(state) {
      state.counter++; // Incrementing the counter value
    },

    // Reducer for decrementing the counter by 1
    decrement(state) {
      state.counter--; // Decrementing the counter value
    },

    // Reducer for increasing the counter by a specific amount
    increase(state, action) {
      state.counter = state.counter + action.payload; // Adding the payload value to the counter
    },

    // Reducer for toggling the visibility of the counter
    toggleCounter(state) {
      state.showCounter = !state.showCounter; // Toggling the showCounter value
    },
  },
});

// Exporting action creators generated by createSlice for the counter slice
export const counterActions = counterSlice.actions;

// Exporting the reducer function generated by createSlice for the counter slice
export default counterSlice.reducer;

/*
The createSlice function from Redux Toolkit is used to define a slice of the Redux store that manages the counter state.
The slice is given a name ('counter') to identify it within the Redux store.
The initial state for the counter slice is defined with properties counter initialized to 0 and showCounter initialized to true.
Inside the reducers object, individual reducer functions are defined to handle specific actions:
increment: Increments the counter value by 1.
decrement: Decrements the counter value by 1.
increase: Increases the counter value by a specified payload amount.
toggleCounter: Toggles the visibility of the counter by flipping the value of showCounter.
Action creators generated by createSlice are exported as counterActions.
The reducer function generated by createSlice for the counter slice is exported as the default export.
*/
